import sqlite3
import uuid
from pathlib import Path

DB_PATH = Path(__file__).resolve().parents[2] / "data" / "db.db"


def addUserIntoDatabaseByName(name: str):
    print(f"Adding user {name} into database")

    # Recleaning for security
    clean_name = name.strip()
    if not clean_name:
        return {"status": "error", "message": "Nom vide"}

    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON;")
    cursor = conn.cursor()

    try:
        # Disclaimer : The SQL Requests executed in SQLite
        # have been generated by AI and reviewed by us

        # Checking if this name has already been saved into DB and do nothing if so
        cursor.execute("SELECT 1 FROM cv_profiles WHERE nom = ? LIMIT 1", (clean_name,))
        exists = cursor.fetchone() is not None
        if exists:
            return {"status": "exists", "message": "Nom déjà présent, aucune insertion"}

        # Else insert a new line with only name
        new_id = str(uuid.uuid4())
        cursor.execute(
            """
            INSERT INTO cv_profiles (id_user_page, nom, prenom, tel, email, adresse, id_user_mail)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (new_id, clean_name, "", "", "", "", "")
        )
        conn.commit()
        return {"status": "created", "message": "Utilisateur créé"}
    finally:
        conn.close()


def addUserIntoDatabaseByFirstname(firstname: str):
    print(f"Adding user {firstname} into database")


def addUserIntoDatabaseByEmail(email: str):
    print(f"Adding user {email} into database")