import sqlite3
import uuid

DB_PATH = "data/db.db"

def getUserFromDatabaseByName(name: str):
    print(f"Getting user {name} from database")

    # Recleaning for security
    clean_name = name.strip()
    if not clean_name:
        return {"status": "error", "message": "Nom vide"}
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    try:
        # Disclaimer : The SQL Requests executed in SQLite 
        #have been generated by AI and reviewed by us 

        # Checking if this name as already been saved into DB and getting it if so
        cursor.execute("SELECT * FROM user_page WHERE nom = ? LIMIT 1", (clean_name,))
        user_data = cursor.fetchone()
        if user_data is None:
            return {"status": "not_found", "message": "Nom non trouvé"}
            
        return {"status": "found", "data": user_data}
    finally:
        conn.close()