from python.database.connection import get_connection


def getUserFromDatabaseByName(name: str):
    # Recleaning for security
    clean_name = name.strip()
    if not clean_name:
        return {"status": "error", "message": "Nom vide"}

    conn = get_connection()
    cursor = conn.cursor()

    try:
        # Disclaimer : The SQL Requests executed in SQLite
        # have been generated by AI and reviewed by us

        # Checking if this name has already been saved into DB and getting it if so
        cursor.execute("SELECT * FROM cv_profiles WHERE nom = ? LIMIT 1", (clean_name,))
        user_data = cursor.fetchone()
        if user_data is None:
            return {"status": "not_found", "message": "Nom non trouvé"}

        return {"status": "found", "data": user_data}
    finally:
        conn.close()
